06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/Animal.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{

    [Table("TB_ANIMAAL")] 
    public class Animal
    {
        [HiddenInput]
        public int AnimalId { get; set; }

        [MaxLength(50)]
        public string Nome { get; set; }

        public bool Carnivoro { get; set; }

        [Display(Name ="TipoAnimal")]
        public TipoAnimal Tipo { get; set; }
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _05_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/Tipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    public enum Tipo
    {
        Particular,Publico
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/TipoAnimal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    public enum TipoAnimal
    {
        Mamifero, Reptil, Ave 
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/Zoo.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{

    [Table("TB_ZOO")]

    public class Zoo 
    {
       
        [Column("Id"), HiddenInput]
        public int ZooId { get; set; }

        [Column("Jaula")]
        public int Jaulas { get; set; }

        [Column("Data Abertura")]
        [DataType(DataType.Date),Display(Name="Data Abertura")]
        public DateTime DataAbertura { get; set; }

        [Required,MaxLength(50),Column("Nome")]
        public string Nome { get; set; }

        [Column("Entidade administradora")]
        [Display(Name ="Tipo")]
        public Tipo EntidadeAdministradora { get; set; }
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _05_Fiap.Web.AspNet.Models;
using _05_Fiap.Web.AspNet.Persistence;
using DocumentFormat.OpenXml.EMMA;
using Microsoft.AspNetCore.Mvc;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class AnimalController : Controller
    {
        private AllZooContext _context;


        public AnimalController(AllZooContext context)
        {
            _context = context;
        }


        ///RETORNA UMA LISTA
        [HttpGet]
        public IActionResult Listar()
        {
            return View(_context.Animals.ToList());
        }




        // CADASTRA
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Cadastrar(Animal animal)
        {
            _context.Animals.Add(animal);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado !";
            return RedirectToAction("Listar");
        }


        //ATUALIZAR
        [HttpGet]
        public IActionResult Atualizar(int id)
        {
            var animal = _context.Animals.Find(id);
            return View(animal);
        }

        [HttpPost]
        public IActionResult Atualizar(Animal animal, Model model)
        {
            _context.Animals.Update(animal);
            _context.SaveChanges();
            TempData["msg"] = "Atualizado !";
            return RedirectToAction("Listar");
        }

        //  Remover seria um metodo [HttpGet] mas por conta do modal que usarmos para passar um Id O metodo muda para [HttpPost]
        [HttpPost]
        public IActionResult Remover(int id)

        {
            var anil = _context.Animals.Find(id);
            _context.Animals.Remove(anil);
            _context.SaveChanges();
            TempData["msg"] = "Removido !";
            return RedirectToAction("Listar");
        }
     

    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _05_Fiap.Web.AspNet.Models;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Controllers/ZooController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _05_Fiap.Web.AspNet.Models;
using _05_Fiap.Web.AspNet.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class ZooController : Controller
    {
       // private static IList<Zoo> _lista = new List<Zoo>();

        private AllZooContext _context;

       public ZooController(AllZooContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Listar()
        {

            return View(_context.Zoos.ToList());
        }


        // CADASTRAR
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Zoo zoo)
        {
            _context.Zoos.Add(zoo);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado com sucesso";
            return RedirectToAction("Listar");
        }


        //ATUALIZAR
        [HttpGet]
        public IActionResult Atualizar(int id)
        {
           var zoo = _context.Zoos.Find(id);
     
            return View(zoo);
        }

        [HttpPost]
        public IActionResult Atualizar(Zoo zoo)
        {
            _context.Zoos.Update(zoo);
            _context.SaveChanges();
            TempData["msg"] = "Atualizado !";
            return RedirectToAction("Listar");
        }

        // REMOVER
        [HttpPost]
        public IActionResult Remover (int id)
        {
            var zoo = _context.Zoos.Find(id);
            _context.Zoos.Remove(zoo);
            _context.SaveChanges();
            TempData["msg"] = "Removido !";

            return RedirectToAction("Listar");
        }
    }
}

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Animal/Atualizar.cshtml
@model Animal
@{
    ViewData["Title"] = "Atualizar";
}

<div class="alert alert-success">@TempData["msg"]</div>

<h1>Atualizar</h1>

<div class="row">
    <div class="col-md-4">

        <form asp-action="Atualizar">
            <input asp-for="AnimalId" />
       
            <partial name="_formulario" />
            <botao texto="Atualizar" />

            @* arrumar do cancelar*@
            <a asp-action="Listar" asp-controller="animal" class="btn btn-danger">Cancelar</a>
        </form>

    </div>
</div>

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Animal/Cadastrar.cshtml
@model Animal
<h1>CADASTRAR ANIMAL</h1>

<form asp-action="Cadastrar" asp-controller="Animal">
    <partial name="_formulario" />
    <botao texto="Cadastrar" />
</form>

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Animal/Listar.cshtml
@model IList<Animal>
@{
    ViewData["Title"] = "Listar";
}

    <mensagem texto="@TempData["msg"]"></mensagem>
<h1>Listar</h1>

<table class="table">
    <tr>

        <th>CODIGO</th>
        <th>NOME</th>
        <th>CARNIVORO</th>
        <th>TIPO ANIMAL</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AnimalId</td>
            <td>@item.Nome</td>
            <td>@item.Carnivoro</td>
            <td>@item.Tipo</td>
            <td>
                <a asp-action="Atualizar" asp-controller="Animal" asp-route-id="@item.AnimalId" class="btn btn-primary">Atualizar</a>
                @*Onclick referencia a id passada no modal*@
                <a asp-action="Remover" onclick="churros.value = @item.AnimalId" asp-controller="Animal" class="btn btn-danger" asp-route-id="@item.AnimalId" data-toggle="modal" data-target="#modalExemplo">Remover</a>
            </td>
        </tr>
    }
</table>

<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Confirmar exclusao </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Deseja realmente excluir ??
        </div>
        <div class="modal-footer">
            <form asp-action="remover">
                @*ID para ser referenciado no botao remover *@
                <input type="hidden" name="id" id="churros" />

                <button type="button" class="btn btn-secondary" data-dismiss="modal">Nao</button>
                @*Para realizar o delete e preciso usar-lo como type=submit *@
                <button type="submit" class="btn btn-primary">Sim</button>
            </form>
        </div>
    </div>
</div>
</div>

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Animal/_formulario.cshtml
@model Animal


<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Tipo"></label>
    <select asp-for="Tipo" class="form-control" asp-items="@Html.GetEnumSelectList<TipoAnimal>()">
        <option>Selecione</option>
    </select>
</div>
<div class="form-group">
    <label asp-for="Carnivoro"></label>
    <input asp-for="Carnivoro" class="form-check" />
</div>

06-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _05_Fiap.Web.AspNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">- FORMULARIO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="zoo" asp-action="cadastrar">Cadastrar Zoologico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="zoo" asp-action="listar">Lista zoologico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="animal" asp-action="Cadastrar">Cadastrar Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="animal" asp-action="Listar">Lista Animais</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - _05_Fiap.Web.AspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>