05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/Zoo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    public class Zoo
    {
        public int Jaulas { get; set; }

        [DataType(DataType.Date),Display(Name="Data Abertura")]
        public DateTime DataAbertura { get; set; }
        public string Nome { get; set; }

        [Display(Name ="Tipo")]
        public Tipo EntidadeAdministradora { get; set; }
    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Controllers/ZooController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _05_Fiap.Web.AspNet.Models;
using Microsoft.AspNetCore.Mvc;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class ZooController : Controller
    {


        private static IList<Zoo> _lista = new List<Zoo>();

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Listar()
        {
            return View(_lista);
        }




        [HttpPost]
        public IActionResult Cadastrar(Zoo zoo)
        {
            _lista.Add(zoo);
            TempData["msg"] = "Cadastrado com sucesso";
            return RedirectToAction("Listar");
        }
    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Zoo/Cadastrar.cshtml
@model Zoo

@{
   
} 

<h1>Zoo</h1>


<form asp-action="Cadastrar" asp-controller="Zoo">
    <div class="form-group">
        <label asp-for="Jaulas"></label>
        <input asp-for="Jaulas" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="DataAbertura"></label>
        <input asp-for="DataAbertura" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="EntidadeAdministradora"></label>
        <select asp-for="EntidadeAdministradora" class="form-control"
                asp-items="@Html.GetEnumSelectList<Tipo>()">
            <option>Selecione</option>
        </select>
    </div>
    <botao></botao>
</form>

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Zoo/Listar.cshtml
@model IList<Zoo>

@{
    ViewData["Title"] = "Listar";
}

<h1>Listar</h1>

<div class="alert alert-success">@TempData["msg"]</div>

@* <mensagem texto="@TempData["msg"]"></mensagem>*@

<table class="table">
    <tr>
        <th>NOME</th>
        <th>JAULAS</th>
        <th>ADMINISTRADORA</th>
        <th>DATA ABERTURA </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Jaulas</td>
            <td>@item.EntidadeAdministradora</td>
            <td>@item.DataAbertura.ToShortDateString()</td>
        </tr>
    }
</table>